### ISSUE TITLE
mxnet.base.MXNetError: [11:42:46] src/operator/contrib/./rnnt_loss-inl.h:218: Check failed: dshape[0] == lshape[0] (474 vs. 1) The batch size for the labels and data arrays must be the same.

### ISSUE THREAD

**Issue by Marcovaldong** [HawkAaron/RNN-Transducer#11]
When I run the code and I get the current error. I try to get the size of variable ytu, ys, their size are 1x474x60x62 and 1x59, is there something wrong?

Traceback (most recent call last):
  File "train.py", line 133, in <module>
    train()
  File "train.py", line 99, in train
    loss = model(xs, ys, xlen, ylen)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 360, in __call__
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/kaldi_io/kaldi_io.py", line 82, in cleanup
    raise SubprocessFailed('cmd %s returned %d !' % (cmd,ret))
kaldi_io.kaldi_io.SubprocessFailed: cmd copy-feats scp:data/train/feats.scp ark:- | apply-cmvn --utt2spk=ark:data/train/utt2spk scp:data/train/cmvn.scp ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- | nnet-forward data/final.feature_transform ark:- ark:-  returned 141 !

    return self.forward(*args)
  File "/disk2/dongsq/asr/RNN-Transducer/model.py", line 87, in forward
    loss = self.loss(ytu, ys, xlen, ylen)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 360, in __call__
    return self.forward(*args)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 575, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/disk2/dongsq/asr/RNN-Transducer/rnnt_mx.py", line 24, in hybrid_forward
    blank_label=self.blank_label)
  File "<string>", line 75, in RNNTLoss
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/_ctypes/ndarray.py", line 92, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/base.py", line 146, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:42:46] src/operator/contrib/./rnnt_loss-inl.h:218: Check failed: dshape[0] == lshape[0] (474 vs. 1) The batch size for the labels and data arrays must be the same.

**Comment by yannhan** [comment]
I have the same issue as you yesterday, you just need to update the latest rnnt_mx.py file. The bug will be fixed.

**Comment by Marcovaldong** [comment]
I noticed that, then I got another error: 

Traceback (most recent call last):
  File "train.py", line 133, in <module>
    train()
  File "train.py", line 99, in train
    loss = model(xs, ys, xlen, ylen)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 360, in __call__
    return self.forward(*args)
  File "/disk2/dongsq/asr/RNN-Transducer/model.py", line 88, in forward
    loss = self.loss(ytu, ys, xlen, ylen)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 360, in __call__
    return self.forward(*args)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 575, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/disk2/dongsq/asr/RNN-Transducer/rnnt_mx.py", line 15, in hybrid_forward
    loss = F.contrib.RNNTLoss(pred, label.astype('int32', False), 
TypeError: astype() takes 2 positional arguments but 3 were given
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/kaldi_io/kaldi_io.py", line 82, in cleanup
    raise SubprocessFailed('cmd %s returned %d !' % (cmd,ret))
kaldi_io.kaldi_io.SubprocessFailed: cmd copy-feats scp:data/train/feats.scp ark:- | apply-cmvn --utt2spk=ark:data/train/utt2spk scp:data/train/cmvn.scp ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- | nnet-forward data/final.feature_transform ark:- ark:-  returned 141 !

**Comment by yannhan** [comment]
I am also confused...astype() takes 2 positional arguments, but ('int32', False) are just 2 arguments... where is the 3rd one?

**Comment by Marcovaldong** [comment]
> I am also confused...astype() takes 2 positional arguments, but ('int32', False) are just 2 arguments... where is the 3rd one?

Enen, I don't why I can get this error, can you reproduce it?

**Comment by yannhan** [comment]
My training process is okay, but the testing process has some bugs that haven't been fixed. You can check another issue that I created before yours.

**Comment by Marcovaldong** [comment]
I got another error when I ran the code form the master branch, is it possible that there is something wrong about my environment? 

Traceback (most recent call last):
  File "train.py", line 130, in <module>
    train()
  File "train.py", line 96, in train
    loss = model(xs, ys, xlen, ylen)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 360, in __call__
    return self.forward(*args)
  File "/disk2/dongsq/RNN-Transducer/model.py", line 60, in forward
    loss = self.loss(f, g, ys, xlen, ylen)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 360, in __call__
    return self.forward(*args)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 575, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
TypeError: hybrid_forward() takes 6 positional arguments but 7 were given
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/kaldi_io/kaldi_io.py", line 82, in cleanup
    raise SubprocessFailed('cmd %s returned %d !' % (cmd,ret))
kaldi_io.kaldi_io.SubprocessFailed: cmd copy-feats scp:data/train/feats.scp ark:- | apply-cmvn --utt2spk=ark:data/train/utt2spk scp:data/train/cmvn.scp ark:- ark:- | add-deltas --delta-order=1 ark:- ark:- | nnet-forward data/final.feature_transform ark:- ark:-  returned 141 !

**Comment by Marcovaldong** [comment]
I copied the code of MxNet from the dir of incubator-mxnet/python/mxnet where I compiled it to the dir of python3.6/lib/python3.6/site-packages/mxnet, will it infere the running of the code?

**Comment by yannhan** [comment]
I think you don't need to copy, I didn't copy.

**Comment by Marcovaldong** [comment]
I removed the dir of python3.6/lib/python3.6/site-packages/mxnet and recovered the state of installing mxnet by source code, there still has the same error.

**Comment by Marcovaldong** [comment]
I changed the code of the function RNNTLoss from label.astype('int32', False) to label.astype('int32'), then it can run successfully.

**Comment by HawkAaron** [comment]
@Marcovaldong 
For the first problem (astype), if the api in mxnet 1.1 doesn't work, remove `False` would be ok.

For the second problem, it seems that you used the master branch, you'd better checkout to `graves2013` and run it again.

**Comment by Marcovaldong** [comment]
@HawkAaron Thanks for your reply, I have solved the first problem.

**Comment by Marcovaldong** [comment]
@ Did you fix the problem of testing process?

**Comment by Marcovaldong** [comment]
@hsama95  Did you fix the problem of the testing process?

**Comment by yannhan** [comment]
I have fixed, but the result is very bad...80% CER. @HawkAaron told me that my model didn't converge. But my loss didn't decrease after 20 epochs. The final train loss is about 114, still too large. I am trying adam optimizer now. But I think it may be my data's problem.

**Comment by Marcovaldong** [comment]
@hsama95  I got the current error when running the eval script, did you got it? 

Traceback (most recent call last):
  File "eval.py", line 79, in <module>
    decode()
  File "eval.py", line 71, in decode
    y = [pmap[rephone[i]] for i in y]
  File "eval.py", line 71, in <listcomp>
    y = [pmap[rephone[i]] for i in y]
KeyError: 'sil'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/disk2/dongsq/environments/python3.6/lib/python3.6/site-packages/kaldi_io/kaldi_io.py", line 82, in cleanup
    raise SubprocessFailed('cmd %s returned %d !' % (cmd,ret))
kaldi_io.kaldi_io.SubprocessFailed: cmd copy-feats scp:data/test/feats.scp ark:- | apply-cmvn --utt2spk=ark:data/test/utt2spk scp:data/test/cmvn.scp ark:- ark:- | add-deltas --delta-order=2 ark:- ark:- | nnet-forward data/final.feature_transform ark:- ark:-  returned 141 !

**Comment by Marcovaldong** [comment]
@HawkAaron  Can you explain what the meaning of phones.60-48-39.map is?

**Comment by HawkAaron** [comment]
@Marcovaldong That is TIMIT phone mapping file, generally we train models on 60 or 48 phoneme set, when decoding, we map it to 39 phoneme set. For more details, please check [kaldi recipe].(https://github.com/kaldi-asr/kaldi/blob/master/egs/timit/README.txt)
