### ISSUE TITLE
DataLoader.py return these errors...

### ISSUE THREAD

**Issue by oshindow** [HawkAaron/RNN-Transducer#24]
################################################################################
################################################################################

{'<eps>': 0, 'sil': 1, 'aa': 2, 'ae': 3, 'ah': 4, 'ao': 5, 'aw': 6, 'ax': 7, 'ay': 8, 'b': 9, 'ch': 10, 'cl': 11, 'd': 12, 'dh': 13, 'dx': 14, 'eh': 15, 'el': 16, 'en': 17, 'epi': 18, 'er': 19, 'ey': 20, 'f': 21, 'g': 22, 'hh': 23, 'ih': 24, 'ix': 25, 'iy': 26, 'jh': 27, 'k': 28, 'l': 29, 'm': 30, 'n': 31, 'ng': 32, 'ow': 33, 'oy': 34, 'p': 35, 'r': 36, 's': 37, 'sh': 38, 't': 39, 'th': 40, 'uh': 41, 'uw': 42, 'v': 43, 'vcl': 44, 'w': 45, 'y': 46, 'z': 47, 'zh': 48, '#0': 49, '#1': 50}
/home/wxt/kaldi/src/featbin/copy-feats scp:data/train/feats.scp ark:- 
/home/wxt/kaldi/src/featbin/apply-cmvn --utt2spk=ark:data/train/utt2spk scp:data/train/cmvn.scp ark:- ark:- 
/home/wxt/kaldi/src/featbin/add-deltas --delta-order=2 ark:- ark:- 
/home/wxt/kaldi/src/nnetbin/nnet-forward data/final.feature_transform ark:- ark:- 
Traceback (most recent call last):
  File "/home/wxt/kaldi/egs/timit/s5/DataLoader.py", line 118, in <module>
    SequentialLoader('train')._dump()
  File "/home/wxt/kaldi/egs/timit/s5/DataLoader.py", line 63, in _dump
    with open('data-npy/'+k+'.y', 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data-npy/FAEM0_SI1392.y'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wxt/RNNTgraves2013/venv/lib/python3.6/site-packages/kaldi_io/kaldi_io.py", line 97, in cleanup
    raise SubprocessFailed('cmd %s returned %d !' % (cmd,ret))
kaldi_io.kaldi_io.SubprocessFailed: cmd /home/wxt/kaldi/src/featbin/copy-feats scp:data/train/feats.scp ark:- | /home/wxt/kaldi/src/featbin/apply-cmvn --utt2spk=ark:data/train/utt2spk scp:data/train/cmvn.scp ark:- ark:- | /home/wxt/kaldi/src/featbin/add-deltas --delta-order=2 ark:- ark:- | /home/wxt/kaldi/src/nnetbin/nnet-forward data/final.feature_transform ark:- ark:-  returned 141 !

**Comment by HawkAaron** [comment]
Sorry for late reply. Maybe you need to create 'data-npy' dir first.
